platform :ios, '7.0'
xcodeproj 'chimehack.xcodeproj'
workspace 'chimehack.xcworkspace'

# Opensource Approved
pod 'MNColorKit', :head
pod 'AutoLayoutShorthand', :podspec => './PodSpecs/AutoLayoutShorthand.podspec'
pod 'AFNetworking'
pod 'UIAlertView+Blocks'
