common: &common
  adapter: mysql2
  encoding: utf8
  socket: /tmp/mysql.sock
  pool: 5

local: &local
  <<: *common
  reconnect: false
  pool: 5
  username: root
  password:

development:
  database: chimehack_development
  <<: *local

test:
  database: chimehack_test
  <<: *local

production: &production
  username: DUNNOYET
  password: STOPLOOKINGATME
  host: local_who_knows
  database: yeah_as_if_id_tell_you
  <<: *common
